### ISSUE TITLE
Numero del badge disallineato

### ISSUE THREAD

**Issue by zetareticoli** [italia/bootstrap-italia#1081]
## Versione di Bootstrap Italia

v2.8.2

## Comportamento atteso
Il numero previsto dal `Badge` nel componente `Bottomnav` deve essere allineato al centro.

## Comportamento attuale

Il numero risulta disallineato perché eredita alcune declarations globali:
```css
p, ul, ol, dl {
  font-size: 1.125rem;
  line-height: 1.75rem;
}
```

## Possibili soluzioni

Specificare un valore di `line-height` per il testo inserito nel badge.

## Contesto

![Screenshot 2024-03-05 alle 17 50 46](https://github.com/italia/bootstrap-italia/assets/69706/c25d8aab-d82f-4d52-ad1d-8b71a5e943c4)

Riscontrato su browser Safari, Chrome.
