### ISSUE TITLE
Classi `.text-`doppie

### ISSUE THREAD

**Issue by zetareticoli** [italia/bootstrap-italia#1159]
## Comportamento atteso

Avere un'unica lista di classi `.text-{color-name}` dedicate al colore del testo, che sovascrivino quelle di default della libreria Bootstrap e richiamando le variabili dei design tokens.

## Comportamento attuale

Nel file `bootstrap-italia-min` vengono compilate due liste di classi dedicate al colore del testo:
- quelle originale di Bootstrap, che usano le CSS variables
- quelle generate da Bootstrap Italia, che usano variabili Sass compilate in `hex`

Ci troviamo quindi classi doppione poste in punti diversi del foglio di stile compilato:

**Classe di Bootstrap - riga 13511**
```css
.text-primary {
  --bs-text-opacity: 1;
  color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important
}
```

**Classe di Bootstrap Italia - riga 17180**
```css
.text-primary {
  color: #06c
}
```

## Possibili soluzioni

Personalizzare i colori della libreria Bootstrap, sovrascrivendo le variabili colore di default senza generare classi doppie. Aggiungere invece classi nuove nel caso siano necessarie.

Esempio: `.text-muted` non prevista da libreria Bootstrap
