### ISSUE TITLE
Sostituire la direttiva `@import` con `@use`

### ISSUE THREAD

**Issue by zetareticoli** [italia/bootstrap-italia#1309]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Versione della libreria

latest

### Cosa

Modificare l'importazione di parziali `*.scss` utilizzando la direttiva moderna `@use`.

[Documentazione](https://sass-lang.com/documentation/at-rules/import/)

### Perché

La direttiva `@import` è obsoleta e sarà presto deprecata.

### Altro

Nel caso di importazione di parziali con stesso nome, ma estensione diversa (esempio, design token) è necessario adottare un alias. 

Esempio:

```scss
@use "../../node_modules/design-tokens-italia/css/_variables.css" as cssVars;
@use "../../node_modules/design-tokens-italia/scss/_variables" as scssVars;

// Uso delle variabili
body {
  color: cssVars.var(--primary-color); // Variabile CSS
  margin: scssVars.$spacing;          // Variabile SCSS
}
```
